notes on upgrading prettier
navikt/platforce-doc pull request #48
Opened 2024-07-16 15:42 UTC by nocturnalnematode

.

2024-07-16 16:26 UTC, Triopticon submitted a review, later dismissed

2024-07-22 14:39 UTC, Triopticon submitted a review, later dismissed

2024-07-29 08:24 UTC, Triopticon requested changes

2024-07-29 08:24 UTC, Triopticon commented on Makefile
Dette virker ikkje på windows!

2024-07-29 10:57 UTC, nocturnalnematode commented on Makefile
det ante meg. vet du hvorfor?

2024-07-29 11:03 UTC, nocturnalnematode commented on Makefile
lagt på en mulig fiks

2024-07-29 11:04 UTC, Triopticon commented on Makefile
Fordi cp ikkje er ein cmd kommando i Windows. Den fungerer som alias for Copy-Item i PowerShell, men du kan ikkje garantere at bruker bruker PowerShell i Windows. :-)

2024-07-29 11:15 UTC, nocturnalnematode commented on Makefile
> lagt på en mulig fiks

^

2024-07-29 11:17 UTC, Triopticon approved these changes

2024-07-29 11:17 UTC, Triopticon commented on Makefile
Mulig den fiksen virker ettersom copy funker i cmd og er alias i PowerShell. Gjerne få Frode til å kjøre denne og sjå om det funker ok for han.

2024-07-29 12:20 UTC, merged